/*
* generated by Xtext
*/
package dk.itu.bddctransform.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LettuceOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
