/*
 * generated by Xtext
 */
package dk.itu.bddcontracts.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GherkinUiModule extends dk.itu.bddcontracts.ui.AbstractGherkinUiModule {
	public GherkinUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
