/*
* generated by Xtext
*/
package dk.itu.bddcontracts.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class GherkinOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
