/*
* generated by Xtext
*/
package dk.itu.bddcontracts.ui.contentassist;

import dk.itu.bddcontracts.ui.contentassist.AbstractGherkinProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GherkinProposalProvider extends AbstractGherkinProposalProvider {

}
