/*
* generated by Xtext
*/
package dk.itu.bddctransform.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.itu.bddctransform.services.LettuceGrammarAccess;

public class LettuceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LettuceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.itu.bddctransform.parser.antlr.internal.InternalLettuceParser createParser(XtextTokenStream stream) {
		return new dk.itu.bddctransform.parser.antlr.internal.InternalLettuceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TransformModel_";
	}
	
	public LettuceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LettuceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
