/*
 * generated by Xtext
 */
package dk.itu.bddctransform.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LettuceUiModule extends dk.itu.bddctransform.ui.AbstractLettuceUiModule {
	public LettuceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
