/*
 * generated by Xtext
 */
package dk.itu.bddctransform;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LettuceRuntimeModule extends dk.itu.bddctransform.AbstractLettuceRuntimeModule {

}
