/*
 * generated by Xtext
 */
package dk.itu.bddctransform.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.bddctransform.ui.internal.LettuceActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LettuceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LettuceActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LettuceActivator.getInstance().getInjector(LettuceActivator.DK_ITU_BDDCTRANSFORM_LETTUCE);
	}
	
}
