/*
 * generated by Xtext
 */
package dk.itu.simplifiedjml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TomatoUiModule extends dk.itu.simplifiedjml.ui.AbstractTomatoUiModule {
	public TomatoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
