/*
* generated by Xtext
*/
package dk.itu.simplifiedjml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.itu.simplifiedjml.services.TomatoGrammarAccess;

public class TomatoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TomatoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.itu.simplifiedjml.parser.antlr.internal.InternalTomatoParser createParser(XtextTokenStream stream) {
		return new dk.itu.simplifiedjml.parser.antlr.internal.InternalTomatoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SimplifiedJMLModel";
	}
	
	public TomatoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TomatoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
