/*
* generated by Xtext
*/
package dk.itu.simplifiedjml.ui.contentassist;

import dk.itu.simplifiedjml.ui.contentassist.AbstractTomatoProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TomatoProposalProvider extends AbstractTomatoProposalProvider {

}
