/*
 * generated by Xtext
 */
package dk.itu.simplifiedjml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.simplifiedjml.ui.internal.TomatoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TomatoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TomatoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TomatoActivator.getInstance().getInjector(TomatoActivator.DK_ITU_SIMPLIFIEDJML_TOMATO);
	}
	
}
