/*
* generated by Xtext
*/
package dk.itu.bddctransform.ui.contentassist;

import dk.itu.bddctransform.ui.contentassist.AbstractLettuceProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LettuceProposalProvider extends AbstractLettuceProposalProvider {

}
