/*
 * generated by Xtext
 */
package dk.itu.simplifiedjml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TomatoRuntimeModule extends dk.itu.simplifiedjml.AbstractTomatoRuntimeModule {

}
